### ISSUE TITLE
Unlocking the car also re-enables the car

### ISSUE THREAD

**Issue by PERPGamer** [eurofra1d/BaitCarPro#1]
When you disable the car and then unlock it, the car becomes enabled again meaning the suspect can drive again. Is there a way to keep the car disabled when you unlock it and only re-enables with you use the repair button?

**Comment by eurofra1d** [comment]
Unlocking it should only allow the suspect to get out of the car, car shouldn’t be able to drive. Have you changed anything in the code? Will test again to make sure I didn’t introduce any bugs before I realeased but it definitely worked the way you describe before

**Comment by PERPGamer** [comment]
> Unlocking it should only allow the suspect to get out of the car, car shouldn’t be able to drive. Have you changed anything in the code? Will test again to make sure I didn’t introduce any bugs before I realeased but it definitely worked the way you describe before

I have not changed anything but for some reason, the moment the unlock button is pressed the car is able to driven again. I'm unsure why

**Comment by lFARVA** [comment]
I had the same issue - no modifications to the code.

**Comment by PERPGamer** [comment]
Any updates?

**Comment by HumanTree92** [comment]
I had submit a PR that should fix this.
